### ISSUE TITLE
[BUG] Tad interaction with 8444 port. 

### ISSUE THREAD

**Issue by realbluefish** [Tad-Network/tad-blockchain#10] opened 2021-07-27 13:04 UTC
TAD interaction with 8444. Cause problems in chia.
I can see it with poweshell command. Port 8444 already block with TIME WAIT forever in 0 system process

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop**

- OS: 
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by fabitom** [comment] 2021-07-31 21:48
can't reproduce, are you sure its not released previous instance ?

**Comment by TheTad** [comment] 2021-08-09 22:13
Hello
I could not reproduce that too!

```
(venv) ~ TAD % netstat -ntap | grep tad | grep LISTEN           
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:4456          0.0.0.0:*               LISTEN      330114/tad_wallet   
tcp        0      0 127.0.0.1:4457          0.0.0.0:*               LISTEN      401451/tad_farmer   
tcp        0      0 127.0.0.1:4458          0.0.0.0:*               LISTEN      401452/tad_harveste 
tcp        0      0 127.0.0.1:4555          0.0.0.0:*               LISTEN      330115/tad_full_nod 
tcp        0      0 0.0.0.0:4044            0.0.0.0:*               LISTEN      330115/tad_full_nod 
tcp        0      0 127.0.0.1:4400          0.0.0.0:*               LISTEN      329779/tad_daemon   
tcp        0      0 0.0.0.0:4447            0.0.0.0:*               LISTEN      401451/tad_farmer   
```

**Comment by TheTad** [comment] 2021-08-09 22:35
I'm closing this issue unless new information is presented

Thank you!

**Closed as completed by TheTad** 2021-08-09 22:35 UTC
Labels: bug
